check:
  - thoth-precommit
  - thoth-build
build:
  build-stratergy: Source
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.29.0
  custom-tag: latest
  registry: quay.io
  registry-org: harshad16
  registry-project: s2i-test-notebook
  registry-secret: thoth-station-thoth-pusher-secret

  # build-stratergy: "Dockerfile"
  # registry: "quay.io"
  # registry-org: "harshad16"
  # registry-project: "test"
  # registry-secret: "thoth-station-thoth-pusher-secret"
  # custom-tag: "latest"
# deploy:
#   project-org: "harshad16"
#   project-name: "thoth-application"
#   image-name: "test"
#   overlay-contextpath: "test/overlays/test/imagestreamtag.yaml"
