apiVersion: v1
kind: Template
metadata:
  name: openshift-test
  labels:
    template: openshift-test
    app: test
    component: openshift-test

objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      labels:
        app: test
        component: openshift-test
      name: openshift-test
    spec:
      name: ${IMAGE_STREAM_TAG}

  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      creationTimestamp: null
      labels:
        app: test
        component: openshift-test
      name: openshift-test
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: openshift-test:latest
      postCommit: {}
      resources: {}
      source:
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      strategy:
        dockerStrategy:
          dockerfilePath: Dockerfile.centos
          noCache: true
      triggers:
        - type: ConfigChange
        - type: ImageChange
          automatic: {}


parameters:
  - description: Name of the github repository
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/harshad16/test'

  - description: Git reference to be used
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: 'master'

  - description: Tag of the ImageStream to use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'
